# Generated by Django 4.2.15 on 2024-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('price_band', models.CharField(max_length=100)),
                ('open_date', models.CharField(blank=True, max_length=100, null=True)),
                ('close_date', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_size', models.CharField(max_length=100)),
                ('listing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('rhip_dhrp', models.CharField(max_length=50)),
            ],
        ),
    ]
